# Generated by Django 3.2.3 on 2021-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_room', models.SmallIntegerField(db_index=True, help_text='первая цифра указывает на этаж', unique=True, verbose_name='номер комнаты')),
                ('number_of_sleep_place', models.CharField(choices=[('2', 'двухместный'), ('3', 'трёхместный'), ('4', 'четырехместный')], max_length=3, verbose_name='количество спальных мест')),
                ('sleep_place', models.CharField(help_text='диван/кровать', max_length=64, verbose_name='тип спального места')),
                ('view', models.TextField(verbose_name='описание вида из окна')),
                ('air_conditioning', models.BooleanField(verbose_name='есть кондей?')),
                ('refrigerator', models.BooleanField(verbose_name='есть холодос?')),
                ('balcony', models.BooleanField(verbose_name='есть балкон?')),
            ],
        ),
    ]
