# Generated by Django 3.2.3 on 2021-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sleep_place',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view',
        ),
        migrations.AddField(
            model_name='room',
            name='window_view',
            field=models.CharField(choices=[('sea', 'вид на море'), ('mountains', 'вид на горы'), ('town', 'вид на город')], default=None, max_length=128, verbose_name='описание вида из окна'),
            preserve_default=False,
        ),
    ]
