# Generated by Django 3.2.3 on 2021-05-25 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_auto_20210525_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(related_name='liked_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
